# Site settings
title: "gjuniioor"
bye_message: "Thx!"
baseurl:
url: "https://jongseok6598.github.io"
disqus: 

# Header settings
nick: "jongseok"
mail:"jongseok6598@gmail.com"
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "jongseok"
blog:
    server: "wordpress.com"
    nick: "jongseok"
fingerprint_key: "안녕하세요"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
