# Site settings
title: "jongseok"
bye_message: "Thx!"
baseurl: "/clyell/"
url: "https://jongseok6598.github.io/"
disqus: jongseok

# Header settings
nick: "jongseok"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "jongseok"
blog:
    server: "wordpress.com"
    nick: "jongseok"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
